version: '3'

services:

  postgres:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432
    restart: always
    networks:
      - airnet

  adminer:
    image: adminer
    container_name: postgresql-adminer
    ports:
      - 8085:8080
    restart: always
    networks:
      - airnet

  airflow:
    build: .
    container_name: airflow-1
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__FERNET_KEY=HXJmviZ45J6R0bM1DFFij0JJ1ca_JMDWo9Z-Q-wqsFk=
      - AIRFLOW__WEBSERVER__SECRET_KEY=b27dfe9846d048294adc0df96ad43239fa325db739a0a69a60672e3e6272
    ports:
      - 8001:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
    networks:
      - airnet

networks:
  airnet:
    driver: bridge